spring.application.name=api-pagamentos
spring.datasource.url=jdbc:mysql://localhost:3306/api_pagamentos
spring.datasource.username=root
spring.datasource.password=matheus20101958

server.port=8081
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
stripe.api.key=sk_test_placeholder_key
stripe.webhook.secret=whsec_placeholder_secret